# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-08 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('disciplines_id', models.AutoField(primary_key=True, serialize=False)),
                ('disciplines_name', models.TextField(max_length=100)),
                ('hours', models.IntegerField()),
                ('form', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_year', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('disciplines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Disciplines')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('specialty_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialty_name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('form_training', models.CharField(max_length=200)),
                ('group', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Student'),
        ),
        migrations.AddField(
            model_name='disciplines',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Specialty'),
        ),
    ]
